options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'docker.io/arulrajah/cloud-native-web-app:$SHORT_SHA'
      - '.'

  # Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'docker.io/arulrajah/cloud-native-web-app:$SHORT_SHA'

  # Deploy to Kubernetes
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/cloud-native-web-app'
      - 'cloud-native-web-app=docker.io/arulrajah/cloud-native-web-app:$SHORT_SHA'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'

images:
  - 'docker.io/arulrajah/cloud-native-web-app:$SHORT_SHA'